### ISSUE TITLE
Improve reproduceability

### ISSUE THREAD

**Issue by Anaphory** [simuling/simuling#24]
Work with more transparent RNGs and RNG seeding to enable reproducing results.

**Comment by Anaphory** [comment]
-  [X] Add seed switch to tree generator

**Comment by LinguList** [comment]
I don't know whether you know this already, but for dictionaries and specific python stuff, we further need to fix how things are ordered from command line. We tested this with Gerhard Jäger for a paper on LingPy, and I can dig it out.

**Comment by Anaphory** [comment]
Oh, right dictionary salting. Do you want me to prioritize that things can be exactly, minutely reproduced? Because then I need to do that before I delve into the evaluation bits.

**Comment by LinguList** [comment]
I personally do not too much care about this now, but I know also well that this may be a bad idea to not care about it, so I suggest that I leave this question to you, as you're teh expert on how to run simulations.

**Comment by Anaphory** [comment]
I don't care much yet. I think it will be useful once this is public and people want to do more detailed comparisons, because then the small details one might get out of a simulation run might matter, and therefore replicability will be an issue.

**Comment by Anaphory** [comment]
In the process of re-implementation, I have found an idea on how to make calibration run faster using multiprocessing. That implementation would require a minor change in our current seed-based way of tracking the pseudo-RNG reproduceability, but it's still a gimmick, not something required, so this issue stays open.
